# Generated by Django 4.2.5 on 2023-10-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeValue',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'time_value',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeValueAggregated',
            fields=[
                ('minute', models.DateTimeField(primary_key=True, serialize=False)),
                ('avg_value', models.FloatField()),
            ],
            options={
                'db_table': 'minute_aggregated',
                'ordering': ['-minute'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TimeValueMax',
            fields=[
                ('time', models.DateTimeField(primary_key=True, serialize=False)),
                ('value', models.FloatField()),
            ],
            options={
                'db_table': 'time_value_max',
                'ordering': ['-time'],
                'managed': False,
            },
        ),
    ]
